name = "type-s-web"
compatibility_date = "2024-01-01"
main = "./dist/_worker.js"

# Build configuration
[build]
command = "pnpm build"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "type-s-db"
database_id = "4f70f843-2817-4c0e-910a-5a1a02362bb8"
migrations_dir = "./drizzle/migrations"
preview_database_id = "DB"

# Development configuration
[dev]
port = 4321
